runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /edit-scholarship
  script: unused
  login: optional
  secure: optional
- url: /logins
  script: unused
  login: optional
  secure: optional
- url: /display-ToDoList
  script: unused
  login: optional
  secure: optional
- url: /delete-scholarship
  script: unused
  login: optional
  secure: optional
- url: /list-scholarships
  script: unused
  login: optional
  secure: optional
- url: /current-user
  script: unused
  login: optional
  secure: optional
- url: /update-vote
  script: unused
  login: optional
  secure: optional
- url: /data
  script: unused
  login: optional
  secure: optional
- url: /delete-Info
  script: unused
  login: optional
  secure: optional
- url: /edit-Info
  script: unused
  login: optional
  secure: optional
- url: /info
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
